// vue-stack/src/App.vue
<template>
  <div id="app">
    <div class="router">
      <ul>
        <li v-for="route of routes" :key="route.path">
          <router-link :to="route.path">{{ route.path }}</router-link>
        </li>
      </ul>
    </div>
    <div class="page">
      <router-view></router-view>
    </div>
  </div>
</template>

<script>
import { routes } from "./router";

export default {
  name: "App",
  data() {
    return {
      routes
    };
  }
};
</script>

<style lang="css">
.router {
  display: flex;
  background: #ddd3d3;
}
.page {
  margin-top: 120px;
}
</style>

// react-stack/src/App.tsx
import React from "react";
import "./App.css";
import { BrowserRouter, NavLink, Route, Switch } from "react-router-dom";
import * as pages from "./pages";

const Navigation = () => (
  <>
    {Object.values(pages).map((Page) => (
      <p key={Page.name}>
        <NavLink to={`/${Page.name}`}>{Page.name}</NavLink>
      </p>
    ))}
  </>
);

const Switcher = () => (
  <>
    <Switch>
      {Object.values(pages).map((Page) => (
        <Route key={Page.name} path={`/${Page.name}`} component={Page} />
      ))}
    </Switch>
  </>
);

function App() {
  return (
    <div className="App">
      <BrowserRouter>
        <Navigation />
        <p>---</p>
        <Switcher />
      </BrowserRouter>
    </div>
  );
}

export default App;
